title: Coding Capybara
email: barber@hey.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jorshasaur
logo: "/assets/images/capy.svg"

author:
  name: "Josh Barber"
  bio: "This is an amazing bio!"

# Build settings
#theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark
plugins:
  - jekyll-feed
  - jekyll-include-cache
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: false
      read_time: true
      author_profile: true
      paginate: 0
